version: '3.7'

services:

  # Backend API
  face-rec-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-rec-api
    environment:
      POSTGRES_DB: face-rec-docker
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
    links:
      - postgres
    ports:
      - '3001:3001'
    volumes:
      - ./:/usr/src/face-rec-api

  # Postgres
  postgres:
    build: ./postgres
    ports:
      - '1234:5432'
    environment:
      POSTGRES_DB: face-rec-docker
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres